version: 2

updates:
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    reviewers:
      - "Sage-Bionetworks/rocc-maitainers"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    reviewers:
      - "Sage-Bionetworks/rocc-maitainers"

  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    reviewers:
      - "Sage-Bionetworks/rocc-maitainers"
